version: '3'
services:
  web:
    build: .
    command: bin/dev
    tty: true
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "7654:3000"
    networks:
      - chord-suggestor-network
  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chord-suggestor-network
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

networks:
  chord-suggestor-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

volumes:
  mysql-data:
    driver: local
